#!/usr/bin/env python3
"""Write a promotion baton bottle from workflow inputs."""
import json, sys, hashlib, os

output_dir = sys.argv[1]
agent_name = sys.argv[2]
agent_role = sys.argv[3]
agent_model = sys.argv[4]
agent_source = sys.argv[5]
target_level = sys.argv[6]
gauntlet_profile = sys.argv[7]

from datetime import datetime, timezone
ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
slug = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
agent_lower = agent_name.lower().replace(" ", "-")

baton = {
    "type": "I2I:PROMOTE",
    "version": "2.0",
    "from": agent_name,
    "to": "market-manifold-fleet",
    "level": target_level,
    "timestamp": ts,
    "gauntlet_profile": gauntlet_profile,
    "shard": {
        "artifacts": {
            "agent_name": agent_name,
            "agent_role": agent_role,
            "agent_model": agent_model,
            "agent_source": agent_source,
            "gauntlet": gauntlet_profile
        },
        "reasoning": [
            f"Agent {agent_name} seeks promotion to {target_level}",
            f"Gauntlet profile: {gauntlet_profile}",
            f"Promotion baton generated by CI/CD pipeline at {ts}"
        ],
        "blockers": []
    }
}

# Compute integrity
shard_json = json.dumps(baton["shard"], separators=(",", ":"), sort_keys=True)
baton["integrity"] = hashlib.sha256(shard_json.encode()).hexdigest()

os.makedirs(output_dir, exist_ok=True)
filename = f"{slug}-{agent_lower}-promotion.baton"
path = os.path.join(output_dir, filename)
with open(path, "w") as f:
    json.dump(baton, f, indent=2)

# Also output the baton path
print(path)
